# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLh1xXT8qoPGmWFtfPmOxG9qEkRE_QGE

**API call using python**
"""

pip install flickrapi # installing flickrapi library

from flickrapi import FlickrAPI
import json
api_key = u'c1343949333e1bf54e31efa19294a38c'
api_secret = u'35c0c06125b887f7'
flickr = FlickrAPI(api_key, api_secret, format='parsed-json')
meow = flickr.photos.getPopular(user_id = '73509078@N00') # some random user 
# print(type(meow))
print(meow)
json_formatted_str = json.dumps(meow, indent=2) # printing it in a proper form
print(json_formatted_str)